---
- name: Playbook to modify clamav config
  hosts: '{{ server }}'
  become: yes
  become_method: sudo
  gather_facts: true
  roles:
    - { role: roles/clamav_modify_config_el7, when: ansible_distribution_major_version|int == 7 }
    - { role: roles/clamav_modify_config_el6, when: ansible_distribution_major_version|int == 6 }

