---
- hosts: Gentoo
  tasks: 
  - name: Create folder for installer
    stat:
      path: /etc/portage/package.accept_keywords
    register: stat_result

  - name: Create the file, if it doesnt exist already
    file:
      path: /etc/portage/package.accept_keywords
      state: touch
    when: stat_result.stat.exists == False
    become: true
      
  - name: Add netdata entry in package.accept_keywords if not present
    lineinfile:
      path: /etc/portage/package.accept_keywords
      line: '=net-analyzer/netdata-1.9.0 ~amd64'
    become: true

  - name: Emerge netdata
    command: emerge -q netdata
    become: true