---
- hosts: NotGentoo
  tasks: 
  - name: Create folder for installer
    file:
      path: /home/ans/netdata
      state: directory
      mode: 0755
  - name: Copy netdata kickstart.sh installer file
    copy:
      src: /home/ans/myplatform/files/kickstart.sh
      dest: /home/ans/netdata/kickstart.sh
      owner: ans
      mode: 0755
  - name: Run netdata installer
    command: /home/ans/netdata/kickstart.sh --dont-wait
    become: true