---
- hosts: all
  tasks: 
  - name: Create folder for installer
    file:
      path: /home/ans/netdata
      state: directory
      mode: 0755
  - name: Download netdata kickstart.sh installer file
    get_url:
      url: https://my-netdata.io/kickstart.sh
      dest: /home/ans/netdata
      mode: 0775
  - name: Run netdata installer
    command: /home/ans/netdata/kickstart.sh all --dont-wait
    become: true