---
- name: Playbook to modify /etc/nagios/nrpe.cfg
  hosts: '{{ server }}'
  become: yes
  become_method: sudo
  gather_facts: false
  tasks:
  - name: Copy /etc/nagios/nrpe.cfg
    copy:
     src: /etc/nagios/nrpe.cfg
     dest: /etc/nagios/nrpe.cfg
     owner: root
     group: root
     mode: 0644
     backup: true
  - name: restart the service
    service:
     name: xinetd
     state: restarted