---
- hosts: <hostname_or_ip>  #Change <hostname_or_ip> to the actual entry in the Ansible hosts file.
  become: yes
  become_method: sudo
  become_user: root
  tasks:
  - name: Gather the package facts
    ansible.builtin.package_facts:
      manager: auto
  - name: Copy rhel6 net-snmp-libs 5.5 rpm
    copy:
      src: <file_location>  #Change <file_location> to the actual file location.
      dest: /tmp
    when:
      - ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "6"
      - packages == "net-snmp" and net-snmp['version'] < "5.5"
