- name: veeam_user
  hosts: host_group
  ansible.builtin.user:
    name: username
    comment: Veeam_Service_Account
    password: "<password_hash>"
    shell: /bin/bash
    groups: wheel
    state: present
    createhome: yes